image: alpine/edge
packages:
  - meson
  - cairo-dev
  - wayland-dev
  - wayland-protocols
  - libxkbcommon-dev
  - gdk-pixbuf-dev
  - linux-pam-dev
  - scdoc
sources:
  - https://github.com/swaywm/swaylock
tasks:
  - setup: |
      cd swaylock
      meson build
  - build-both: |
      cd swaylock
      ninja -C build
  - build-pam: |
      cd swaylock
      meson build-pam -Dshadow=disabled
      ninja -C build
  - build-shadow: |
      cd swaylock
      meson build-shadow -Dpam=disabled
      ninja -C build
